# Task

[Matrix multiplication](https://en.wikipedia.org/wiki/Matrix_multiplication) is a fundamental linear algebraic operation, working knowledge of which is a prerequisite to understanding modern neural networks. In this assignment, you will implement matrix multiplication in pure Python (`python_matmul`) and in Python using NumPy (`numpy_matmul`). Skeletal versions of the two functions are provided in the included Python source file.

This assignment is an opportunity for you to assess your preparedness for the course. It does not count towards your final grade.

In [0]:
import numpy as np

In [0]:
def python_matmul(X, Y):
    """
    Multiply 2-dimensional list arrays using pure Python.

    Parameters
    ----------
    X : list
    A list of M elements, each of which is an N-element list.
    Y : list
    A list of N elements, each of which is a K-element list.

    Returns
    ----------
    A list of M elements, each of which is a K-element list.
    """
    if not isinstance(X, list):
        raise ValueError('X must be list')
    if not isinstance(Y, list):
        raise ValueError('Y must be list')
    if not isinstance(X[0], list):
        raise ValueError('X must be 2-dimensional')
    if not isinstance(Y[0], list):
        raise ValueError('Y must be 2-dimensional')
    if not len(X[0]) == len(Y):
        raise ValueError('Column length of X must equal row length of Y')

    # Create a 2-dim array of zeros.  Must use iteration to avoid reference sharing.
    r = [[0]*len(Y[0]) for _ in range(len(X))]
 
    for i in range(len(X)):
        for j in range(len(Y[0])):
            for k in range(len(Y)):
                r[i][j] += X[i][k] * Y[k][j]

    return r


In [0]:
def numpy_matmul(X, Y):
    """
    Multiply 2-dimensional numpy arrays using PEP-0465 infix operator.

    Parameters
    ----------
    X : np.ndarray
        An MxN array.
    Y : np.ndarray
        An NxK array.

    Returns
    ----------
    An MxK array.
    """
    
    if not isinstance(X, np.ndarray):
        raise ValueError('X must be ndarray')
    if not isinstance(Y, np.ndarray):
        raise ValueError('Y must be ndarray')
    if not X.ndim == 2:
        raise ValueError('X must be 2-dimensional')
    if not Y.ndim == 2:
        raise ValueError('Y must be 2-dimensional')
    if X.shape[1] != Y.shape[0]:
        raise ValueError(
            'Columns of X ({:d}) must equal rows of Y ({:d}'.format(
                X.shape[1], Y.shape[0]))

    # numpy makes this easy
    return X.dot(Y)

In [61]:
# Test Code for matrix multiplication routines
X = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9,10,11,12]]

Y = [[23,22,21,20,19,18],
     [17,16,15,14,13,12],
     [11,10, 9, 8, 7, 6],
     [ 5, 4, 3, 2, 1, 0]]

print("Python")
print(python_matmul(X,Y))

print("numpy")
print(numpy_matmul(np.array(X), np.array(Y)))

Python
[[110, 100, 90, 80, 70, 60], [334, 308, 282, 256, 230, 204], [558, 516, 474, 432, 390, 348]]
numpy
[[110 100  90  80  70  60]
 [334 308 282 256 230 204]
 [558 516 474 432 390 348]]


# Survey
Briefly describe your (research) interest in deep learning/machine learning in the cell below.

I am a part time student pursuing a course-based MS in Computer Science, so I don't specifically have a research interest.  

I work full-time as a Firmware Engineer for a large manufacturer of Hard Disc Drives (HDD's).  Specifically, I work in the division which produces scripts and firmware for the automated calibration and certification testing of HDD's in high-volume mass production.  My interest in Machine Learning revolves around finding methods to improve any combination of: product quality,  production yields, and/or manufacturing test time for the HDD units produced in our manufacturing facilities.  

